// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: symbiotic-fp/protobuf/symbiotic_fp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRootSignIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids           string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	L1BlockNumber uint64 `protobuf:"varint,2,opt,name=l1_block_number,json=l1BlockNumber,proto3" json:"l1_block_number,omitempty"`
}

func (x *StateRootSignIDsRequest) Reset() {
	*x = StateRootSignIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateRootSignIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRootSignIDsRequest) ProtoMessage() {}

func (x *StateRootSignIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRootSignIDsRequest.ProtoReflect.Descriptor instead.
func (*StateRootSignIDsRequest) Descriptor() ([]byte, []int) {
	return file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescGZIP(), []int{0}
}

func (x *StateRootSignIDsRequest) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

func (x *StateRootSignIDsRequest) GetL1BlockNumber() uint64 {
	if x != nil {
		return x.L1BlockNumber
	}
	return 0
}

type StateRootSignIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StateRootSignIDsResponse) Reset() {
	*x = StateRootSignIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateRootSignIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRootSignIDsResponse) ProtoMessage() {}

func (x *StateRootSignIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRootSignIDsResponse.ProtoReflect.Descriptor instead.
func (*StateRootSignIDsResponse) Descriptor() ([]byte, []int) {
	return file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescGZIP(), []int{1}
}

func (x *StateRootSignIDsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StateRootSignIDsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_symbiotic_fp_protobuf_symbiotic_fp_proto protoreflect.FileDescriptor

var file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDesc = []byte{
	0x0a, 0x28, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x2d, 0x66, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x74, 0x69,
	0x63, 0x5f, 0x66, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x73, 0x79, 0x6d, 0x62,
	0x69, 0x6f, 0x74, 0x69, 0x63, 0x5f, 0x66, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72,
	0x70, 0x63, 0x22, 0x53, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12,
	0x26, 0x0a, 0x0f, 0x6c, 0x31, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x31, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x88, 0x01, 0x0a, 0x0f, 0x43, 0x65, 0x6c, 0x65,
	0x73, 0x74, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x73, 0x12,
	0x2f, 0x2e, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x5f, 0x66, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x30, 0x2e, 0x73, 0x79, 0x6d, 0x62, 0x69, 0x6f, 0x74, 0x69, 0x63, 0x5f, 0x66, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescOnce sync.Once
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescData = file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDesc
)

func file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescGZIP() []byte {
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescOnce.Do(func() {
		file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescData = protoimpl.X.CompressGZIP(file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescData)
	})
	return file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDescData
}

var file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_symbiotic_fp_protobuf_symbiotic_fp_proto_goTypes = []interface{}{
	(*StateRootSignIDsRequest)(nil),  // 0: symbiotic_fp.proto_rpc.StateRootSignIDsRequest
	(*StateRootSignIDsResponse)(nil), // 1: symbiotic_fp.proto_rpc.StateRootSignIDsResponse
}
var file_symbiotic_fp_protobuf_symbiotic_fp_proto_depIdxs = []int32{
	0, // 0: symbiotic_fp.proto_rpc.CelestiaService.StateRootSignIDs:input_type -> symbiotic_fp.proto_rpc.StateRootSignIDsRequest
	1, // 1: symbiotic_fp.proto_rpc.CelestiaService.StateRootSignIDs:output_type -> symbiotic_fp.proto_rpc.StateRootSignIDsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symbiotic_fp_protobuf_symbiotic_fp_proto_init() }
func file_symbiotic_fp_protobuf_symbiotic_fp_proto_init() {
	if File_symbiotic_fp_protobuf_symbiotic_fp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateRootSignIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateRootSignIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symbiotic_fp_protobuf_symbiotic_fp_proto_goTypes,
		DependencyIndexes: file_symbiotic_fp_protobuf_symbiotic_fp_proto_depIdxs,
		MessageInfos:      file_symbiotic_fp_protobuf_symbiotic_fp_proto_msgTypes,
	}.Build()
	File_symbiotic_fp_protobuf_symbiotic_fp_proto = out.File
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_rawDesc = nil
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_goTypes = nil
	file_symbiotic_fp_protobuf_symbiotic_fp_proto_depIdxs = nil
}
