name: Deploy Test

on:
  workflow_run:
    workflows: ["build-image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-argocd:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ArgoCD repo
        uses: actions/checkout@v4
        with:
          repository: Manta-Network/manta-apps
          token: ${{ secrets.MANTA_GITHUB_TOKEN }}

      - name: Download image tag artifact from previous workflow
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          gh run download $RUN_ID --repo Manta-Network/manta-fp-aggregator --name image-tag
          cat image-tag.txt
        env:
          GH_TOKEN: ${{ secrets.MANTA_GITHUB_TOKEN }}

      - name: Extract new image tag
        run: echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Update ArgoCD manifests
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main

          for file in prod/manta-ap-test/manta-fp-testnet/manta-fp-aggregator-*/values.yaml; do
            if [ -f "$file" ]; then
              sed -i "s|tag: \".*\"|tag: \"${IMAGE_TAG}\"|" "$file"
              echo "Updated tag in $file"
            fi
          done

      - name: Commit and push changes
        run: |
          git commit -am "[From Github Action] Update testnet manta-fp-aggregator image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin main
